### ISSUE TITLE
Windows-ported version

### ISSUE THREAD

**Issue by raimis** [dgasmith/gau2grid#15]
Would it be possible to tag 757e6153f1e01df9c8e467a294e845da444e763e, so in https://github.com/psi4/psi4/pull/1124 I could refer to a tag rather than a hash.

**Comment by dgasmith** [comment]
[Done!](https://github.com/dgasmith/gau2grid/releases/tag/v1.2.0).

**Comment by raimis** [comment]
Thanks!
