### ISSUE TITLE
Tagged version doesn't match CMake project version

### ISSUE THREAD

**Issue by raimis** [dgasmith/gau2grid#16]
Tagged version doesn't match CMake project version:
https://github.com/dgasmith/gau2grid/blob/757e6153f1e01df9c8e467a294e845da444e763e/CMakeLists.txt#L4

As a result, *Psi4* configuration fails: https://travis-ci.org/psi4/psi4/jobs/412702471

**Comment by dgasmith** [comment]
Fixed, thanks for the report.
