### ISSUE TITLE
Update Build Cartesian Orders

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/gau2grid#19]
As @loriab pointed out the `molden` order is not hooked up to build.

The following lines (at least) need to be fixed:
https://github.com/dgasmith/gau2grid/blob/master/CMakeLists.txt#L17, https://github.com/dgasmith/gau2grid/blob/master/CMakeLists.txt#L33, https://github.com/dgasmith/gau2grid/blob/master/cmake/gau2gridConfig.cmake.in#L50-L54, https://github.com/dgasmith/gau2grid/blob/master/cmake/gau2gridConfig.cmake.in#L17-L18

**Comment by hjjvandam** [comment]
I think there is also a problem with lines:
https://github.com/dgasmith/gau2grid/blob/master/cmake/gau2gridConfig.cmake.in#L58-L62
I cannot find any references to the variable ${PN}_molden_FOUND. Hence I am wondering if @CARTESIAN_ORDER@ is still being used. If not, lines 58 to 62 should probably be removed.

**Comment by dgasmith** [comment]
Ah, is this with master? We removed the need for the components, but not the components themselves.

**Comment by hjjvandam** [comment]
OK, I can just set SPHERICAL_ORDER and CARTESIAN_ORDER when we invoke CMake and I think then everything will work. However, when we don't these variables get replaced with "" in gau2gridConfig.cmake and when we try to use this file it causes an error because one of the arguments of STREQUAL is missing. 
I have also noticed that if I build gau2grid stand alone the gau2gridConfig.cmake file is not even used. I am not sure why or how the NWChemEx build is picking it up.

**Comment by dgasmith** [comment]
gau2gridConfig.cmake is mostly for downstream packages to automatically be consumed. I have popped these in #50 and should solve your problem. @wavefunction91 might have specific recommendations for NWChemEx builds.

**Comment by hjjvandam** [comment]
OK, #50 looks exactly what I was looking for. So, I think I will just wait for that to be merged (or use the cmake branch in the meantime).

**Comment by dgasmith** [comment]
Giving the CMake branch a try would be great! See if there is anything else that could crop up.

**Comment by hjjvandam** [comment]
OK, I will see if I can give that a go (I have to check if our dependency management lets me specify a particular branch).

**Comment by loriab** [comment]
the `gau2gridConfig.cmake` file get consumed upon `find_package(gau2grid CONFIG)` in a `CMakeLists.txt` file.

**Comment by dgasmith** [comment]
Closed by #50.
