### ISSUE TITLE
Add soversion to gau2grid library

### ISSUE THREAD

**Issue by susilehtola** [dgasmith/gau2grid#24]
I need to get this packaged in Fedora so that I can finally update psi4 to the 1.2 series.

However, gau2grid doesn't have an soname, which should be added.
https://fedoraproject.org/wiki/Packaging:Guidelines#Downstream_.so_name_versioning

**Comment by loriab** [comment]
As mentioned, I hate redundant info, and tying SOVERSION to package version seems to me to be just that, as well as skipping over the original intention of the former. Will #28 work for your needs?

**Comment by susilehtola** [comment]
Definitely. I really dislike version based sonaming which forces rebuilding packages all the time.

Susi Lehtola
Sent from my phone so excuse my brevity.


On 22 Oct 2018, at 19.16, Lori A. Burns <notifications@github.com<mailto:notifications@github.com>> wrote:


As mentioned, I hate redundant info, and tying SOVERSION to package version seems to me to be just that, as well as skipping over the original intention of the former. Will #28<https://github.com/dgasmith/gau2grid/pull/28> work for your needs?

**Comment by dgasmith** [comment]
Merged in thanks!
