### ISSUE TITLE
More generic C interface

### ISSUE THREAD

**Issue by wavefunction91** [dgasmith/gau2grid#41]
Note: this is not a bug, just a suggestion for an improvement.

Would it be possible to generate a more generic C interface viz the specification style for Cartesian points into the drivers? Currently, the specification dictates that the Cartesian points be specified as 3 unit-stride arrays of length "N". Specifically what I'm looking for is one of the following

1. A specification which allows a single unit stride array of length 3*N which contains the cartesian points contiguously

2. A more flexible specification which allows the user to specify the stride of the X,Y,Z arrays, e.g. the X array could be length N with stride 3.

**Comment by dgasmith** [comment]
I could be up for overhauling the interface. As a note memory access is already one of the limiting factors in gau2grid, we would need to look into how to unpack a `xyzxyz...` style array quickly. I believe we could still do it in a vectorized manner.

A bit torn on the two interfaces:
 1) Would be less flexible, but we could optimize for it.
 2) Would be more flexible and more canonical C. We could also optimize for it when `stride==1` is current style and `stride==3` is the `xyzxyz` style.

This would coincide with a major version bump where we would also allow any spherical or cartesian order to be returned.

**Comment by wavefunction91** [comment]
Yes, memory access will definitely be the sticking point (as it always
is...), especially because xyz loads will not be along cache lines. Are you
currently packing into contiguous aligned aux memory?

I agree on the interfaces as well. Though one would typically have one vs
the other, it would likely be good if complete flexibility in stride
specification was allowed

**Comment by dgasmith** [comment]
Yes, we pull from the provided `xyz` pointer into a small aligned memory cache like so:
```C
double* PRAGMA_RESTRICT cache_data = (double*)ALIGNED_MALLOC(64, 224 * sizeof(double));
```

The function signatures start [here](https://github.com/dgasmith/gau2grid/blob/master/gau2grid/c_generator.py#L332) and you would need to edit the code that pulls from the input buffers [here](https://github.com/dgasmith/gau2grid/blob/master/gau2grid/c_generator.py#L442).

**Comment by cryos** [comment]
@dgasmith I would love an array of length 3n with x, y, z ordering - this is how we store stuff, and would enable me not to repack. This is a smaller part of the integration effort though, and so is more of a convenience/avoiding some copies. 2 seems like a way of making you do the rearrange for me :slightly_smiling_face:, my x, y, z ordered array I will give you three times with a stride of three and a start offset by one each time.

**Comment by dgasmith** [comment]
Since we are breaking the API for a v2, it seems appropriate to do this.

If we agree to simplify the input to a `xyz*` input where `stride==3` (or greater than 3) will indicate the an array of `xyz xyz ...` or a `stride=4` perhaps `xyzw xyzw...` for those which wish to bake in weights. Or a `stride==1` would indicate a `xx... yy... zz...` style input.

If this works for both @cryos and @wavefunction91 my next PR will be to add this.

**Comment by wavefunction91** [comment]
@dgasmith that sounds perfect to me.

**Comment by cryos** [comment]
Me too, I would really appreciate this change @dgasmith!

**Comment by dgasmith** [comment]
PR #49 is up! I think this may be the last thing preventing a v2.0 release with the new API. It would be great if someone could test the new code in production.

**Comment by wavefunction91** [comment]
@dgasmith, I'll put it into NWX and get back.

**Comment by dgasmith** [comment]
Awesome! I will drop it into Psi4 as well.

**Comment by wavefunction91** [comment]
@dgasmith This works in NWX

**Comment by dgasmith** [comment]
Great! I will try this out in Psi4 this weekend and if all goes well create a v2 release.

**Comment by dgasmith** [comment]
Closing this, v2 is now out.
