### ISSUE TITLE
Function and header prefixes

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/gau2grid#43]
It would be useful to be able to compile multiple versions of gau2grid with different ordering paths. This would require prefixes on all functions and headers.

**Comment by loriab** [comment]
I hope that second sentence means you're actually aiming for compiling a _single_ version with multiple pathways. I'm wanting to avert to openblas situation where a single conda (or whatever) pkg only works for half the downstreams.

**Comment by dgasmith** [comment]
I think this would purely be for static builds with codes that effectively ingest the auto generated c code.

**Comment by loriab** [comment]
So if client uses CCA ordering, they can have a `.so` and a python interface, otherwise `libgg.a` only? That's an ordering carrot, I suppose.

Ok, so long as fns have prefixes, client with alt-ordering gg compiled in should be able to co-exist with "generic" cca `libgg.so`.

**Comment by dgasmith** [comment]
This would be more like generate the code, drop it in the source of another project. No `.so` or `.a` in this case.

**Comment by loriab** [comment]
ah, the simint distribution model, got it. 👍 

just continue generating a decent angular momentum (not 7).

**Comment by dgasmith** [comment]
Invalid issue, we can provide all outputs with a single compiled binary. See #48.

@cryos

**Comment by cryos** [comment]
Perfect, glad to hear you thought of a nice solution without the need for multiple binaries!
