### ISSUE TITLE
Allow for CCA ordering of solid harmonic Gaussians

### ISSUE THREAD

**Issue by wavefunction91** [dgasmith/gau2grid#9]
Currently, the only option for spherical Gaussians is to be returned in the Gaussian ordering
[0, -1, +1, -2, +2, ..., -L, +L]

[CCA](https://github.com/evaleev/libint/wiki/using-modern-CPlusPlus--interface-v22-or-later#solid-harmonic-gaussians-ordering-and-normalization) dictates the order
[-L, -L+1, -L+2, ..., 0, L+1, L+2, ... L]

Both orderings are common place in KS codes, thus this would be a useful option to set at configuration

**Comment by dgasmith** [comment]
You can now specify compiled ordering by the following CMake commands:

```
-DCARTESIAN_ORDER - The cartesian ordering of the basis functions (row)
-DSPHERICAL_ORDER - The spherical ordering of the basis functions (cca, gaussian)
```

You can now also query the library for the compiled ordering with:
```
const char* cartesian_order();
const char* spherical_order();
```

Let me know if you have further issues with integration.

**Comment by loriab** [comment]
A program linking to a pre-built g2g is definitely going to want one or the other, yes?

If so, you'll want to add a "component" like https://github.com/dgasmith/gau2grid/blob/master/cmake/gau2gridConfig.cmake.in#L52-L56, so one can `find_package(gau2grid COMPONENTS cca)` and not get the wrong one.

**Comment by wavefunction91** [comment]
Looks good to me @dgasmith. Feel free to close for the original purpose of the issue, but I agree that a component check would be a good idea

**Comment by dgasmith** [comment]
Ok components are in. Closing, please do let me know if you hit issues spinning this up in your code.
